name: moto_taxi_app
description: Moto-taxi matching app for Cameroon — single app, role-based (client or driver)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.5.6
  firebase_database: ^12.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
